stages:
  - test

test-cnn:
  stage: test
  image: python:3.9.18-alpine
  services:
    - docker:20.10.11-dind
  script:
    - apk --update add docker
    - docker pull tensorflow/serving:latest
    - pip install -r requirements.txt
    - docker run --name cnn_models -p 8501:8501 -v "./model_config.config:/models/model_config.config" -v "./cnn_large:/models/cnn_large" -v "./cnn_small:/models/cnn_small" -t tensorflow/serving:latest  --model_config_file=/models/model_config.config
    - python3 -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    - experimentcicd